### ISSUE TITLE
Suggestion: Devsend work with Ethereum addresses

### ISSUE THREAD

**Issue by Maitlans** [enjin/enjincraft#54]
Right now devsend only works with players online whom have linked their wallets. If the "enj devsend" command supported sending to Ethereum wallets directly without players having to be online this would give the ability for owners to use services like Enjin's DonationCraft or Tebex/BuyCraft which support custom variables to be entered upon purchasing and having the server execute a command that sends to the item to the wallet the user entered.

**Comment by Favorlock** [comment]
We'll looking into implementing this. Will likely just add a check to see if the target starts with 0x and if so treat it as an ethereum address.

**Comment by Favorlock** [comment]
Implemented in PR #58
