### ISSUE TITLE
Suggestion: Wallet - Item Locking & Commands

### ISSUE THREAD

**Issue by Maitlans** [enjin/enjincraft#60]
Please let me know what you guys think of both of these suggestions, I think the Locking items one is sort of essential for certain permission based items, and the commands one would expand customization to what collectibles are able to do with the countless plugins Minecraft has available.

**Locking Items** - An option in each item's config where you're able to lock the item so the player is unable to take it out of the wallet in-game as they don't need to since it has no use for the player to be able to obtain it in their inventory.

**Command Items** - When the item is clicked on the wallet in-game a command will be executed, a cooldown will be applied to when the player is able to click on the item again, it could be a few minutes, days or a one time use item. It would support an option to target the player for example %player% to execute commands on them.

**Comment by Favorlock** [comment]
The first suggestion should be possible to implement as we can simply implement a wallet behavior feature for tokens such that they can a) be checked out from the wallet b) viewed in wallet but not checked out and c) hidden from the wallet and not able to be checked out.

As for command items I really don't know how I feel about this. I would think something like this could be achieved using token permissions to grant players access to a command from another plugin that handles this sort of behavior.

**Comment by Maitlans** [comment]
That would be good yes, I think it would be good to also be able to view it but just not withdraw it, as the display item will help the user know they have the ability to do something & display useful information. And yeah makes sense for the second request, should be able to be done via another custom plugin.

**Comment by Favorlock** [comment]
> I think it would be good to also be able to view it but just not withdraw it, as the display item will help the user know they have the ability to do something & display useful information.

That is what I was referring to with part b (e.g. you can see the item in the wallet but you won't be able to check it out.

**Comment by Favorlock** [comment]
As per our discussion, we are implementing the first suggestion, but we are forgoing the second as we feel that a similar effect can be achieved through similar means.
