### ISSUE TITLE
Development Building Issue

### ISSUE THREAD

**Issue by Maitlans** [enjin/enjincraft#62]
I'm having a little bit of issue building the development build myself, is it because I'm using Java 11? And will this be a problem for server providers which only run in Java 11, pretty sure MCPROHOSTING only uses Java 11? I'm able to build the master branch fine. Thank you. 
https://pastebin.com/BgFYvQet

**Comment by Favorlock** [comment]
Last I checked they used Java 8 at MCPH. I believe I use Java 11 for building the plugin, just with Java 8 as the targeted language level (which is already configured in the build scripts).

This is the error I'm seeing "CmdQr.java:8: error: package com.enjin.minecraft_commons.spigot.map does not exist". Which indicates that you'll need to build and install the latest version of [Enjin Minecraft Commons](https://github.com/enjin/Enjin-Minecraft-Commons).

**Comment by Maitlans** [comment]
Must of been the node I was given, I apologize for my ignorance, spent a few hours trying to research it and figure it out by trying different things but I can't seem to figure out how to install the Enjin Minecraft Commons, I appreciate the help.

**Comment by Favorlock** [comment]
Follow these steps:

1. Clone https://github.com/enjin/Enjin-Minecraft-Commons.git
2. Checkout development branch
3. Open a terminal/command line in the root directory of the project (where gradlew is)
3. Run "gradlew -p spigot clean build installArchives" in a terminal (may need to use gradlew.bat on windows)

**Comment by Maitlans** [comment]
Thank you for the help! I got an error at the final step.
https://pastebin.com/LeCt4TZM

**Comment by Favorlock** [comment]
Not 100% if this is the correct format as I usually use run configuration in IntelliJ but the error you're getting can be fixed with an argument as seen in the following: gradlew -PRELEASE_SIGNING_ENABLED=false -p spigot clean build installArchives

**Comment by Maitlans** [comment]
Thank you this worked!
