### ISSUE TITLE
NBTAPI Console Errors

### ISSUE THREAD

**Issue by Maitlans** [enjin/enjincraft#74]
Server Version: 1.16.1 Paper 101
I'm guessing it is because NBTAPI Currently doesn't support 1.16.1 or the compiled version isn't 1.16.1 compatible.
https://pastebin.com/wGyhPmRD

**Comment by Favorlock** [comment]
Are you using the latest version of the development (or master) branch? We pushed a hotfix to update NBTAPI to a version that works for 1.16 a couple days ago. I haven't had a chance to push a new version of the master branch to the spigot resource yet, but if you're using our development builds then you'll just need to pull and rebuild.

**Comment by Maitlans** [comment]
Hey, thank you, I was using the development branch I just updated and everything works perfectly, Closing issue.
