### ISSUE TITLE
EnjinCraft Plugin Not Working

### ISSUE THREAD

**Issue by EliteTrollingG** [enjin/enjincraft#80]
No matter what I do the EnjinCraft Plugin will not enable, whenever I do /enj it says "Internal error.." and in console it says this
[https://paste.gg/p/anonymous/83695c7854554b3694ef56bbae1c2cb7](url)
I've tried everything I know and nothing will work. I'm on 1.16.5 Paper
My "latest.log"
[https://paste.gg/p/anonymous/55b8ea9cd5f54593aa4fba6557c9b228](url)

My list of plugins:
Plugins (61): AuctionHouse, AureliumSkills, Banknotes*, BuycraftX, ChatItemDisplay, Citizens, ClearLag, CombatLogX, CoreProtect, CrazyEnvoy, CubCustomDrops, CustomEnderChest, DBAPI*, Denizen, DragonSlayer, DragonTimer, dtlTraders, Duels, eco, EcoEnchants, EnjinCraft, EssayStaffChat*, Essentials, EssentialsChat, EssentialsSpawn, floodgate-bukkit, GCoreLegacy, Geyser-Spigot, GoldenCrates, GriefPrevention, GSit, HolographicDisplays, HolographicExtension, ImageDisplays, ItemEdit, LibsDisguises, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NametagEdit*, NexEngine, OreRegeneration, PassiveMode, PerWorldPlugins*, PerWorldServer, PlaceholderAPI, PlayerReport, ProtocolLib, racing, RoseStacker, SpleefX, SuperVanish, SupremeItem, TAB, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard

When I do /plugins EnjinCraft is always red, and I haven't even touched EnjinCraft disabled/enabled worlds in PerWorldPlugin so that's not the issue.

**Comment by Favorlock** [comment]
[15:11:57] [Server thread/WARN]: [EnjinCraft] Invalid app id specified in config.
[15:11:57] [Server thread/WARN]: [EnjinCraft] Invalid app secret specified in config.
[15:11:57] [Server thread/WARN]: [EnjinCraft] Invalid dev address specified in config.

You'll need to configure the plugin before it'll enable properly.
