### ISSUE TITLE
Cannot view purchased Wooden Sword asset in the Minecraft Enjin Wallet

### ISSUE THREAD

**Issue by VoidBl** [enjin/enjincraft#81]
Hi,

I have set up my Minecraft server with spigot_1.16.5.jar and the EnjinCraft v1.1.0 plugin and linked the game to my Enjin Wallet configured for dev mode. 

I have changed the config.yml file on the server with the base URL pointing to https://cloud.enjin.io, configured the app ID, secret and dev-address based on the basic project I set up.

I have purchased my first Infinite Fungible Token asset the Wooden Sword and expected that it would automatically sync to my Enjin wallet to the Minecraft Enhin wallet that I linked. 

Am I missing something?

Regards, Luke

**Comment by Maitlans** [comment]
Hey @VoidBl, the tokens won't automatically be loaded within your server, you will have to integrate them using their token ID and what item you want to display within in-game.
Here are the commands on how to do it
https://github.com/enjin/enjincraft/wiki/Command-Usage#enj-token
