### ISSUE TITLE
[Bug & Suggestion] PlaceholderAPI not working

### ISSUE THREAD

**Issue by Maitlans** [enjin/enjincraft#83]
Hey hope you're doing great, I'm trying to utilize the placeholders and they don't seem to be working, on Enjin's Discord another user also reported that they were trying to use PAPI without any results. When the server is booting up it does give you a message that EnjinCraft successfully hooked up into PlaceholderAPI.

Suggestion: Many plugins utilize PAPI and you're able to do many creative things with such a nice tool, it would be very useful to have these placeholders to make way with extra functionalities with third party plugins. 

%enj_has_nft_ID% = True or False
%enj_has_ft_ID%  = True or False
%enj_has_ft_amount_ID%  = #
%enj_has_nft_amount_ID%   = #

Thank you 🙂

**Comment by Favorlock** [comment]
I just tested with the latest version of PAPI and it's still working fine on my end, so I'm not exactly sure what to tell you. Perhaps it's an issue with the plugins you're using to display the placeholders.

![image](https://user-images.githubusercontent.com/909884/120212638-16429300-c1e7-11eb-9cef-3dc46bfde19c.png)

**Comment by Favorlock** [comment]
Also, if it helps, you may need to prefix the placeholder id with "enjincraft" such that the placeholder becomes "%enjincraft_{placeholder}%".

**Comment by Maitlans** [comment]
> Also, if it helps, you may need to prefix the placeholder id with "enjincraft" such that the placeholder becomes "%enjincraft_{placeholder}%". For example, you must use "%enjincraft_eth_addr%" as PAPI requires the plugin name to be prefixed. My guess this is their way of preventing conflicts between plugins that hook into PAPI.

Hey, thank you this was exactly the issue that was happening I wasn't placing "enjincraft" in front of the placeholders.
