### ISSUE TITLE
Will this work on the JENJ cloud?

### ISSUE THREAD

**Issue by dbusher** [enjin/enjincraft#84]
I installed and configured the plugin but none of the commands work.  Do we have this correct:

platform:
  base-url: "https://jumpnet.cloud.enjin.io/"
  app:
    id: 153
    secret: "my secret code"
    dev-identity-id: 327
locale: "en_US"
debug:
  sdk: false
  plugin: false
  sentry: ""
experimental:
  translate-console-messages: false
interal:
  config-version: 1
permission-blacklist:
  - "minecraft.command.op"
  - "minecraft.command.deop"
  - "minecraft.command.stop"

**Comment by Favorlock** [comment]
It should work on jumpnet. I would recommend checking the console for any errors as the above information isn't really sufficient to know what is going on.

**Comment by dbusher** [comment]
Got it to working! Thanks.
