### ISSUE TITLE
/enj commands not working. Enjin plugin is disabled.

### ISSUE THREAD

**Issue by SwordNF** [enjin/enjincraft#87]
Hi.
I installed Enjincraft on my minecraft server.
I edited the config.yml file.

  base-url: "https://kovan.cloud.enjin.io/"
  app:
    id: ---> I got the app ID from my https://cloud.enjin.io/platform/ account in the Settings
    secret: ---> I got the Secret from my https://cloud.enjin.io/platform/ account in the Settings
    dev-address: I used my Enjin wallet.

I restarted the server and started using the /enj commands but it says "**An internal error occurred while attempting to perform this command.**"

And in the console it says that Enjin craft is disabled.

I also asked this in discord support and was advised by someone to post this issue here as they've never encountered this before too.

![image](https://user-images.githubusercontent.com/86893643/124366051-6649c500-dc7f-11eb-9b44-5999596d08fa.png)

**Comment by Maitlans** [comment]
First issue is that you're using the Ethereum Main net ID and Secret, you'll need to create an account on 
https://kovan.cloud.enjin.io/ to use the kovan base-url. Tho I don't think this alone would cause the /enj wallet command to stop working and the plugin not to load but worth the attempt in correcting it.
