### ISSUE TITLE
NFTs not working on my server.

### ISSUE THREAD

**Issue by bowfun** [enjin/enjincraft#88]
Hello,
I'm trying to add NFTs to my Minecraft server. I'm using Jumpnet. When I try with the Kittenish Friends NFT, it works. But when I try with my BowGalaxy NFT (from the BowGalaxy NFTs project), it tells me "Token was not created." I just want to know what the issue is for when I make my official server NFTs. I am using the name "BowGalaxy" for the NFT.

**Comment by Maitlans** [comment]
Could you please in the settings enable debugging and when you attempt to create the NFT is there any debug error? Also could you provide the steps you're taking to create it like the commands you're executing? Should help further track down the issue.

**Comment by bowfun** [comment]
Ok. Sorry it's taken me so long to get back. I can't get on my server right now, but I'll try to do this later.
