### ISSUE TITLE
Update to 1.18.1?

### ISSUE THREAD

**Issue by SrPeterr** [enjin/enjincraft#94]
Hi!
Any updates on when it will be updated to 1.18.1? NBT has a beta already for 1.18.1 :(

**Comment by NotProniss** [comment]
I too would like to know. Tried it as is but it does seem to break, console spits out a bunch of errors.

**Comment by SrPeterr** [comment]
@NotProniss 

I did send an email to see if EnjinCraft was still in development and this is their response:
>Enjincraft is still in development, not at this precise moment as our main focus is to launch our new products (Wallet 2.0, NFT.io, EFI parachain, and such)

**Comment by NotProniss** [comment]
Ok, thanks for letting me know. :(

**Comment by Maitlans** [comment]
> I too would like to know. Tried it as is but it does seem to break, console spits out a bunch of errors.

I'm in 1.18.1 and I'm not experiencing any errors as you're saying.
Could you please create a pastebin and post the errors you're getting? Please be careful that your logs don't show your dev key.

**Comment by Maitlans** [comment]
Ah I forgot, I compiled my own version of EnjinCraft using the latest NBTAPI Dev version, in the build.gradle file, change the 'nbtapi' into "2.9.0-SNAPSHOT" and compile and then it should work.

**Comment by NotProniss** [comment]
> Ah I forgot, I compiled my own version of EnjinCraft using the latest NBTAPI Dev version, in the build.gradle file, change the 'nbtapi' into "2.9.0-SNAPSHOT" and compile and then it should work.

I'm pretty new to this whole Minecraft server thing, I don't suppose you would be willing to provide the .jar you have built? 
i haven't built a plugin before.

**Comment by Maitlans** [comment]
> > Ah I forgot, I compiled my own version of EnjinCraft using the latest NBTAPI Dev version, in the build.gradle file, change the 'nbtapi' into "2.9.0-SNAPSHOT" and compile and then it should work.
> 
> I'm pretty new to this whole Minecraft server thing, I don't suppose you would be willing to provide the .jar you have built? i haven't built a plugin before.

Here's the steps so you can replicate it, you can download IntelliJ IDEA Community Edition program, download this repo, open the .zip and drag it somewhere then in the Intellij open it and at the bottom right it'll say to import "EnjinCraft Gradle Import" click on it and let it do its thing, then head to the "build.gradle" file and change the "kyoriTextAdapter" to "4.0.1-SNAPSHOT" and "nbtapi" to "2.9.0-SNAPSHOT" after that you'll see on the top right a section called "Gradle" and a section called "enjincraft-master" extend that then go to tasks > build then double click build. 

To find the plugin .jar go to the enjincraft-master folder > spigot > build > libs and it should be "EnjinCraft-Spigot-1.1.1-all"

If you're unable to do the steps I can drop you the .jar but I mostly advice against running anything which doesn't come from the official source.

**Comment by NotProniss** [comment]
pretty sure I followed that and got the following error

`C:\Users\proni\IdeaProjects\enjincraft\spigot\src\main\java\com\enjin\enjincraft\spigot\cmd\player\CmdQr.java:11: error: package com.enjin.minecraft_commons.spigot.map does not exist
import com.enjin.minecraft_commons.spigot.map.ImageRenderer;
`

> > > Ah I forgot, I compiled my own version of EnjinCraft using the latest NBTAPI Dev version, in the build.gradle file, change the 'nbtapi' into "2.9.0-SNAPSHOT" and compile and then it should work.
> > 
> > 
> > I'm pretty new to this whole Minecraft server thing, I don't suppose you would be willing to provide the .jar you have built? i haven't built a plugin before.
> 
> Here's the steps so you can replicate it, you can download IntelliJ IDEA Community Edition program, download this repo, open the .zip and drag it somewhere then in the Intellij open it and at the bottom right it'll say to import "EnjinCraft Gradle Import" click on it and let it do its thing, then head to the "build.gradle" file and change the "kyoriTextAdapter" to "4.0.1-SNAPSHOT" and "nbtapi" to "2.9.0-SNAPSHOT" after that you'll see on the top right a section called "Gradle" and a section called "enjincraft-master" extend that then go to tasks > build then double click build.
> 
> To find the plugin .jar go to the enjincraft-master folder > spigot > build > libs and it should be "EnjinCraft-Spigot-1.1.1-all"
> 
> If you're unable to do the steps I can drop you the .jar but I mostly advice against running anything which doesn't come from the official source.

pretty sure I followed that, and got the following error

`C:\Users\proni\IdeaProjects\enjincraft\spigot\src\main\java\com\enjin\enjincraft\spigot\cmd\player\CmdQr.java:11: error: package com.enjin.minecraft_commons.spigot.map does not exist
import com.enjin.minecraft_commons.spigot.map.ImageRenderer;
`

**Comment by BishopJohnson** [comment]
Hi everyone,

For the time being we will release a snapshot version of EnjinCraft ([1.1.2-SNAPSHOT](https://github.com/enjin/enjincraft/releases/tag/v1.1.2-SNAPSHOT)) which supports Minecraft 1.18 using NBT API's 2.9.0-SNAPSHOT.
